Merge SIMDEV-InterfaceCreation into Dev
bhageneder/OpticalCapstoneComputerVision2023 pull request #68
Opened 2024-03-19 21:37 UTC by bhageneder

2024-03-19 23:01 UTC, Mitchell-Conrad-20 requested changes
See comments

2024-03-19 23:05 UTC, stoneoxmike approved these changes
See comment, otherwise looks like a great framework to start

2024-03-19 23:05 UTC, stoneoxmike commented on src/config/config.cfg
Does the ./ work?

2024-03-19 23:09 UTC, bhageneder commented on src/interfaces/iDetectorClass.py
> +        def getRobotLlist(self):
Pulled it from Detector so they were miss-spelt in detector, fixed both instances.
What do you mean by not in the codebase?

2024-03-19 23:09 UTC, bhageneder commented on src/interfaces/iDetectorClass.py
> +            self.__current_transceiver = -1
Consistent with public methods for both virtual and actual architecture

2024-03-19 23:09 UTC, bhageneder commented on src/sim/controller/classes/vDetectorClass.py
> +class simDetector(iDetector):
Resolved

2024-03-19 23:10 UTC, bhageneder commented on src/sim/controller/threads/vdiscovery.py
Place holder for the time being. Folder would not be tracked without file inside.

2024-03-19 23:11 UTC, bhageneder commented on src/config/config.cfg
Error when running main currently "index out of bound" when accessing transceivers. I believe this was fixed in N-Robots but I don't have that change rn. Will work around it and let you know

2024-03-19 23:15 UTC, Mitchell-Conrad-20 commented on src/interfaces/iDetectorClass.py
> +        def getRobotLlist(self):
these methods are not part of detector

2024-03-19 23:16 UTC, bhageneder commented on src/interfaces/iDetectorClass.py
> +        def getRobotLlist(self):
Gotcha, I must have moved them on accident

2024-03-19 23:18 UTC, stoneoxmike commented on src/config/config.cfg
Don't spend too much time bringing over changes that already exist. We can merge and test it later, just noting it for now

2024-03-19 23:19 UTC, Mitchell-Conrad-20 commented on src/interfaces/iDetectorClass.py
> +        def getRobotLlist(self):
nah I thought about it a bit more, they got removed in the PR that went through _yesterday_, so you didnt do anything wrong

2024-03-19 23:44 UTC, Mitchell-Conrad-20 approved these changes
As long as code still is fully functional im cool with the merge

2024-03-19 23:44 UTC, Mitchell-Conrad-20 commented on src/classes/DetectorClass.py
> +                super().init()
does this still need super.init then?

2024-03-20 00:12 UTC, Mitchell-Conrad-20 commented on src/classes/RobotClass.py
> +class Robot():
remove () after Robot

2024-03-20 00:55 UTC, bhageneder commented on src/config/config.cfg
Wasn't able to test, will just take DEV config for now and modify later

2024-03-20 00:55 UTC, bhageneder commented on src/classes/RobotClass.py
> +class Robot():
resolved

2024-03-22 15:54 UTC, merged